print-progress: true
concurrent: 15
media-concurrent: 6
speed-concurrent: 6
shuffle-test-order: true
check-interval: 360
success-limit: 0
timeout: 3000
alive-test-url: http://gstatic.com/generate_204
speed-test-url: https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/download/v2.21.12/Waifu2x-Extension-GUI-v2.21.12-Portable.7z
min-speed: 512
download-timeout: 10
download-mb: 20
total-speed-limit: 0
listen-port: 127.0.0.1:8199
rename-node: true
node-prefix: ''
node-type: null
filter: null
media-check: false
media-check-timeout: 5
platforms:
- iprisk
- tiktok
- youtube
- netflix
- disney
- openai
- gemini
- claude
- spotify
keep-days: 0
output-dir: /opt/ss-monitor/sub/free/__YOUR_32HEX_TOKEN__
enable-web-ui: false
api-key: ''
callback-script: ''
apprise-api-server: ''
recipient-url: null
notify-title: 🔔 节点状态更新
sub-store-port: ''
sub-store-sync-cron: ''
sub-store-produce-cron: ''
sub-store-push-service: ''
mihomo-overwrite-url: http://127.0.0.1:8199/sub/ACL4SSR_Online_Full.yaml
save-method: local
webdav-url: https://example.com/dav/
webdav-username: admin
webdav-password: admin
github-gist-id: ''
github-token: ''
github-api-mirror: ''
worker-url: https://example.worker.dev
worker-token: 1234567890
s3-endpoint: 127.0.0.1:9000
s3-access-id: ak
s3-secret-key: sk
s3-bucket: public
s3-use-ssl: false
s3-bucket-lookup: auto
sub-urls-retry: 3
sub-urls-concurrent: 8
sub-urls-get-ua: clash.meta (https://github.com/beck-8/subs-check)
github-proxy: ''
proxy: ''
success-rate: 0
dns:
  enable: false
  ipv6: false
  nameserver:
  - https://dns.alidns.com/dns-query
  proxy-server-nameserver:
  - https://dns.alidns.com/dns-query
  default-nameserver:
  - 223.5.5.5
  - 119.29.29.29
sub-urls-remote: []
sub-urls:
- https://raw.githubusercontent.com/SoliSpirit/v2ray-configs/refs/heads/main/Protocols/vless.txt
- https://raw.githubusercontent.com/SoliSpirit/v2ray-configs/refs/heads/main/Protocols/vmess.txt
- https://raw.githubusercontent.com/SoliSpirit/v2ray-configs/refs/heads/main/all_configs.txt
- https://raw.githubusercontent.com/V2RayRoot/V2RayConfig/refs/heads/main/Config/vless.txt
- https://raw.githubusercontent.com/YasserDivaR/pr0xy/refs/heads/main/ShadowSocks2021.txt
- https://raw.githubusercontent.com/acymz/AutoVPN/main/data/V2.txt
- https://raw.githubusercontent.com/acymz/AutoVPN/refs/heads/main/data/V2.txt
- https://raw.githubusercontent.com/andigwandi/free-proxy/main/proxy_list.txt#sinspired/subs-check
- https://raw.githubusercontent.com/asgharkapk/Sub-Config-Extractor/main/output_configs/clash/Ruk1ng001.yaml#sinspired/subs-check
- https://raw.githubusercontent.com/asgharkapk/Sub-Config-Extractor/main/output_configs/mixed/Leon406/SubCrawler/sub/share/a11.yaml#sinspired/subs-check
- https://raw.githubusercontent.com/asgharkapk/Sub-Config-Extractor/main/output_configs/surfboard/Barabama_ndnode.yaml#sinspired/subs-check
- https://raw.githubusercontent.com/asgharkapk/Sub-Config-Extractor/main/output_configs/surfboard/Ruk1ng001.yaml#sinspired/subs-check
- https://raw.githubusercontent.com/barry-far/V2ray-config/main/Splitted-By-Protocol/ss.txt
- https://raw.githubusercontent.com/barry-far/V2ray-config/main/Splitted-By-Protocol/ssr.txt
- https://raw.githubusercontent.com/barry-far/V2ray-config/main/Splitted-By-Protocol/trojan.txt
- https://raw.githubusercontent.com/barry-far/V2ray-config/main/Splitted-By-Protocol/vmess.txt
- https://raw.githubusercontent.com/barry-far/V2ray-config/main/Sub2.txt#sinspired/subs-check
- https://raw.githubusercontent.com/ccpthisbigdog/freedomchina/refs/heads/main/clab.yaml
- https://raw.githubusercontent.com/ccpthisbigdog/freedomchina/refs/heads/main/subdom.txt
- https://raw.githubusercontent.com/darknessm427/IranConfigCollector/main/V2.txt
- https://raw.githubusercontent.com/darknessm427/IranConfigCollector/main/bulk/ss_iran.txt
- https://raw.githubusercontent.com/darknessm427/IranConfigCollector/main/bulk/trojan_iran.txt
- https://raw.githubusercontent.com/darknessm427/IranConfigCollector/main/bulk/vless_iran.txt
- https://raw.githubusercontent.com/darknessm427/IranConfigCollector/main/bulk/vmess_iran.txt
- https://raw.githubusercontent.com/dongchengjie/airport/refs/heads/main/subs/merged/tested_within.yaml
- https://raw.githubusercontent.com/dpangestuw/Free-Proxy/main/allive.txt#sinspired/subs-check
- https://raw.githubusercontent.com/ebrasha/free-v2ray-public-list/main/v2ray-subscription.txt
- https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/clash.yml
- https://raw.githubusercontent.com/free18/v2ray/main/c.yaml
- https://raw.githubusercontent.com/gfpcom/free-proxy-list/main/list/ss.txt
- https://raw.githubusercontent.com/gfpcom/free-proxy-list/main/list/ssr.txt
- https://raw.githubusercontent.com/gfpcom/free-proxy-list/main/list/trojan.txt
- https://raw.githubusercontent.com/gfpcom/free-proxy-list/main/list/vless.txt
- https://raw.githubusercontent.com/gfpcom/free-proxy-list/main/list/vmess.txt
- https://raw.githubusercontent.com/ggborr/FREEE-VPN/main/4V2ray
- https://raw.githubusercontent.com/go4sharing/sub/main/sub.yaml
- https://raw.githubusercontent.com/iboxz/free-v2ray-collector/main/main/vless
- https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/main/Vless-Reality-White-Lists-Rus-Cable.txt#sinspired/subs-check
- https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/main/Vless-Reality-White-Lists-Rus-Mobile.txt#sinspired/subs-check
- https://raw.githubusercontent.com/lagzian/SS-Collector/main/SS/TrinityBase
- https://raw.githubusercontent.com/lagzian/SS-Collector/main/SS/VM_TrinityBase
- https://raw.githubusercontent.com/lagzian/SS-Collector/main/SS/trinity_clash.yaml
- https://raw.githubusercontent.com/leetomlee123/freenode/main/README.md
- https://raw.githubusercontent.com/liMilCo/v2r/main/base64/2.txt#sinspired/subs-check
- https://raw.githubusercontent.com/liMilCo/v2r/main/configs.txt#sinspired/subs-check
- https://raw.githubusercontent.com/mahdibland/SSAggregator/master/sub/sub_merge_yaml.yml
- https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/Eternity
- https://raw.githubusercontent.com/mai19950/clashgithub_com/main/site
- https://raw.githubusercontent.com/mai19950/sites/main/sub/v2ray/base64
- https://raw.githubusercontent.com/mermeroo/V2RAY-CLASH-BASE64-Subscription.Links/main/SUB%20LINKS/All_base64.txt
- https://raw.githubusercontent.com/mfbpn/tg_mfbpn_sub/main/trial.yaml
- https://raw.githubusercontent.com/mfuu/v2ray/master/v2ray
- https://raw.githubusercontent.com/mgit0001/test_clash/main/heima.txt
- https://raw.githubusercontent.com/mheidari98/.proxy/refs/heads/main/all
- https://raw.githubusercontent.com/mheidari98/.proxy/refs/heads/main/vless
- https://raw.githubusercontent.com/miladtahanian/V2RayCFGDumper/refs/heads/main/config.txt
- https://raw.githubusercontent.com/miladtahanian/multi-proxy-config-fetcher/refs/heads/main/configs/proxy_configs.txt
- https://raw.githubusercontent.com/mohamadfg-dev/telegram-v2ray-configs-collector/refs/heads/main/category/vless.txt
- https://raw.githubusercontent.com/officialputuid/KangProxy/KangProxy/xResults/Proxies.txt#sinspired/subs-check
- https://raw.githubusercontent.com/officialputuid/KangProxy/KangProxy/xResults/RAW.txt#sinspired/subs-check
- https://raw.githubusercontent.com/officialputuid/KangProxy/KangProxy/xResults/old-data/RAW.txt#sinspired/subs-check
- https://raw.githubusercontent.com/ovmvo/SubShare/main/sub/permanent/mihomo.yaml#sinspired/subs-check
- https://raw.githubusercontent.com/pachangcheng/mianfeijiedian/refs/heads/main/should.txt
- https://raw.githubusercontent.com/pawdroid/Free-servers/main/sub
- https://raw.githubusercontent.com/peacefish/nodefree/main/sub/proxy_cf.yaml
- https://raw.githubusercontent.com/peasoft/NoMoreWalls/master/list.txt
- https://raw.githubusercontent.com/roosterkid/openproxylist/main/V2RAY_RAW.txt
- https://raw.githubusercontent.com/roosterkid/openproxylist/refs/heads/main/V2RAY_RAW.txt
- https://raw.githubusercontent.com/sakha1370/OpenRay/main/output/all_valid_proxies.txt#sinspired/subs-check
- https://raw.githubusercontent.com/sevcator/5ubscrpt10n/main/mini/m1n1-5ub-14.txt#sinspired/subs-check
- https://raw.githubusercontent.com/sevcator/5ubscrpt10n/main/mini/m1n1-5ub-19.txt#sinspired/subs-check
- https://raw.githubusercontent.com/sevcator/5ubscrpt10n/main/protocols/vl.txt
- https://raw.githubusercontent.com/shabane/kamaji/master/hub/merged.txt
- https://raw.githubusercontent.com/shahidbhutta/Clash/main/Router
- https://raw.githubusercontent.com/shahidbhutta/Clash/main/Router#sinspired/subs-check
- https://raw.githubusercontent.com/sinspired/airport/main/subs/SFZY666.yaml
- https://raw.githubusercontent.com/sinspired/airport/main/subs/aiboboxx.yaml
- https://raw.githubusercontent.com/sinspired/airport/main/subs/blue-Youtube.yaml
- https://raw.githubusercontent.com/sinspired/airport/main/subs/changfengoss.yaml
- https://raw.githubusercontent.com/sinspired/airport/main/subs/coldwater-10.yaml
