# ACME challenge 路徑(80 端口的 server 都 include)
# certbot --webroot 模式會把 token 放到 /var/www/letsencrypt/.well-known/acme-challenge/

location ^~ /.well-known/acme-challenge/ {
    root /var/www/letsencrypt;
    try_files $uri =404;
}
